### ISSUE TITLE
之前用的好好的，突然参数不合法

### ISSUE THREAD

**Issue by ywz978020607** [xdedss/dist_bhpan#1]
pancli.utils.api.ApiException: api returned HTTP 400
{"causemsg":"参数 (path) 的值无效（错误提供者：EFSHttpServer，
错误值：16777222，错误位置：ncEFSDirHandlerV1.cpp:344）","errcode":400002,"errmsg":"参数不合法。"}

**Comment by xdedss** [comment]
有可能和remote_dir后缀斜杠有关，上传文件的时候没有strip掉，现已修复
