### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by zzysteve** [xdedss/dist_bhpan#3]
安装完成后，运行bhpan test，错误如下：

raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bhpan.buaa.edu.cn', port=443): Max retries exceeded with url: /api/v1/auth1/getnew (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by xdedss** [comment]
bhpan.buaa.edu.cn的证书出问题了，[ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=bhpan.buaa.edu.cn&s=106.39.41.86&latest)显示服务器没有返回中间证书，导致requests不认。临时的解决办法是给pancli/utils/api.py 里面每个requests.post、requests.get、requests.put加上参数verify=False。但是可能带来一些安全风险，更好的解决方案等我有时间再研究一下

**Comment by xdedss** [comment]
临时解决方案可以拉dev-sslfix分支
